//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl, Version=1.1.4322.573 自动生成。
// 
namespace QDHBUserService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HBUserServiceSoap", Namespace="http://tempuri.org/")]
    public class HBUserService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public HBUserService() {
            this.Url = "http://10.77.8.205/hbopenservice/HBUserService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHBUserByIP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HBUser GetHBUserByIP(string ip) {
            object[] results = this.Invoke("GetHBUserByIP", new object[] {
                        ip});
            return ((HBUser)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetHBUserByIP(string ip, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetHBUserByIP", new object[] {
                        ip}, callback, asyncState);
        }
        
        /// <remarks/>
        public HBUser EndGetHBUserByIP(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((HBUser)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHBUserByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HBUser GetHBUserByID(string userID) {
            object[] results = this.Invoke("GetHBUserByID", new object[] {
                        userID});
            return ((HBUser)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetHBUserByID(string userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetHBUserByID", new object[] {
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public HBUser EndGetHBUserByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((HBUser)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsUserInRole", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsUserInRole(string logonName, string applicationName, string role) {
            object[] results = this.Invoke("IsUserInRole", new object[] {
                        logonName,
                        applicationName,
                        role});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUserInRole(string logonName, string applicationName, string role, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUserInRole", new object[] {
                        logonName,
                        applicationName,
                        role}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUserInRole(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsUserInRoleTemp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsUserInRoleTemp(string logonName, string applicationName, string role) {
            object[] results = this.Invoke("IsUserInRoleTemp", new object[] {
                        logonName,
                        applicationName,
                        role});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsUserInRoleTemp(string logonName, string applicationName, string role, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsUserInRoleTemp", new object[] {
                        logonName,
                        applicationName,
                        role}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsUserInRoleTemp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentUserRoles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCurrentUserRoles(string logonName, string applicationName) {
            object[] results = this.Invoke("GetCurrentUserRoles", new object[] {
                        logonName,
                        applicationName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCurrentUserRoles(string logonName, string applicationName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCurrentUserRoles", new object[] {
                        logonName,
                        applicationName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetCurrentUserRoles(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentUserFunctions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCurrentUserFunctions(string logonName, string applicationName) {
            object[] results = this.Invoke("GetCurrentUserFunctions", new object[] {
                        logonName,
                        applicationName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCurrentUserFunctions(string logonName, string applicationName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCurrentUserFunctions", new object[] {
                        logonName,
                        applicationName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetCurrentUserFunctions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSignInUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSignInUrl() {
            object[] results = this.Invoke("GetSignInUrl", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSignInUrl(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSignInUrl", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetSignInUrl(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/authentication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool authentication(string logonName, string pwd) {
            object[] results = this.Invoke("authentication", new object[] {
                        logonName,
                        pwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginauthentication(string logonName, string pwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("authentication", new object[] {
                        logonName,
                        pwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endauthentication(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUsers() {
            object[] results = this.Invoke("GetUsers", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUsers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUsers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetUsers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrganizations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrganizations() {
            object[] results = this.Invoke("GetOrganizations", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOrganizations(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrganizations", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetOrganizations(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class HBUser {
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string LogonName;
        
        /// <remarks/>
        public string DisplayName;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string FullPath;
        
        /// <remarks/>
        public string ParentID;
        
        /// <remarks/>
        public string SortID;
        
        /// <remarks/>
        public string GlobalSortID;
        
        /// <remarks/>
        public string TopOU_ID;
        
        /// <remarks/>
        public string TopOU_Name;
        
        /// <remarks/>
        public string SecondaryOU;
        
        /// <remarks/>
        public string CustomsCode;
        
        /// <remarks/>
        public string TopOU_Class;
        
        /// <remarks/>
        public string TopOU_Rank;
        
        /// <remarks/>
        public string ParentType;
        
        /// <remarks/>
        public int Levels;
    }
}
